/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imageo_CUtile */

#ifndef _Included_com_imageo_CUtile
#define _Included_com_imageo_CUtile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imageo_CUtile
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_imageo_CUtile_name
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_imageo_CUtile_callJni
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
